server:
  port: 8080
  servlet:
    context-path: /api/v1/msvc-template

spring:
  application:
    name: msvc-template
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
#    mongodb:
#      database: msvc-template
#      host: host.docker.internal
#      port: 27017

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
