spring:
  profiles:
    active: dev

cartera:
  segmentos:
    uno: https://www.sclpcj.com.mx:7071/CyCRest/cartera-download/search/58921
    clientes: https://www.sclpcj.com.mx:7071/CyCRest/cartera-download/get
    clientegestor: https://www.sclpcj.com.mx:7071/CyCRest/cartera-gestor/datosCliente

pagos:
  planes: https://www.sclpcj.com.mx:7071/PlanesPago/historico-planes
  edocuentas: https://www.sclpcj.com.mx:7071/CyCRest/edoCuentaCU/validaCliente
  edocuentasabonos: https://www.sclpcj.com.mx:7071/CyCRest/edoCuentaCU/abonosCliente/

blasters:
  envioMasivoTTS: https://wsblaster.marcatel.com.mx/ServicioBlaster.svc/mex

gestores:
  obtenerGestores: https://www.sclpcj.com.mx:7071/CyCRest/alta-gestor/obtenerGestores/58921/0
  asignaCartera: https://www.sclpcj.com.mx:7071/CyCRest/cartera-gestor/asignaCartera
  obtenerGestionesSCL: https://www.sclpcj.com.mx:7071/CyCRest/scl-gestiones/consultar

datasource:
  url: jdbc:oracle:thin:@localhost:1521:xe
  username: USERBDCLBAZTKM
  password: UserCobranzaLegalTKMBD23.
  driver-class-name: oracle.jdbc.OracleDriver
